// Libs
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

// TODO: choose new font and update metadata
// would like something like https://fonts.google.com/specimen/Sedan and https://fonts.google.com/specimen/Sedan+SC
const inter = Inter( { subsets: [ 'latin' ] } );
export const metadata: Metadata = {
    title: 'Create Next App'
    , description: 'Generated by create next app'
};

export default function RootLayout ( { children }: Readonly<{ children: ReactNode}> ) {
    return (
        <html lang='en'>
            <body
                className={ inter.className }
                style={ { margin: 0 } }
            >
                <AppRouterCacheProvider>
                    { children }
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
