// Libs
import type { Metadata } from 'next';
import { ReactNode } from 'react';

// MUI
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';

// Styles
import { theme } from '@/theme';
import { Box } from '@mui/material';

// TODO: update metadata
export const metadata: Metadata = {
    title: 'Create Next App'
    , description: 'Generated by create next app'
};

export default function RootLayout ( { children }: Readonly<{ children: ReactNode}> ) {
    return (
        <html lang='en'>
            <Box
                component='body'
                sx={ {
                    margin: 0
                    , bgcolor: '#121212'
                } }
            >

                <ThemeProvider theme={ theme }>
                    <AppRouterCacheProvider>
                        { children }
                    </AppRouterCacheProvider>
                </ThemeProvider>
            </Box>
        </html>
    );
}
